### ISSUE TITLE
Error Loading hy3 File

### ISSUE THREAD

**Issue by hydrostaticcog** [SwimComm/hytek-parser#2]
When I try to load an `hy3` file, I get an error about decoding the file:

```Traceback (most recent call last):
  File "/home/hydro/hytek/main.py", line 6, in <module>
    results = hytek_parser.parse_hy3("286a.hy3")
  File "/home/hydro/.local/lib/python3.9/site-packages/hytek_parser/hy3_parser.py", line 33, in parse_hy3
    lines = [line.strip() for line in f]
  File "/home/hydro/.local/lib/python3.9/site-packages/hytek_parser/hy3_parser.py", line 33, in <listcomp>
    lines = [line.strip() for line in f]
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 5138: invalid continuation byte
```

I used the code that someone gave in #1.

```
import attrs
import hytek_parser
import pprint

results = hytek_parser.parse_hy3("286a.hy3")
d = attrs.asdict(results)

pprint.pprint(d)
```

Python version: 3.10.5 (was able to replicate on 3.9.2)

**Comment by egelja** [comment]
Hmm. Can you send your HY3 file?

**Comment by hydrostaticcog** [comment]
I actually found out the problem. For some reason my LSC posts their hy3 files not UTF-8 encoded, so I just converted it and everything worked fine.
